
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
    networks:
      - tcp-scanner-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tcp-scanner-network
    restart: unless-stopped

networks:
  tcp-scanner-network:
    driver: bridge 